name: Lint JSON

on:
  push:
    paths:
      - 'prod/tagline/android/main.json'
      - 'prod/tagline/iphone/main.json'
  pull_request:
    paths:
      - 'prod/tagline/android/main.json'
      - 'prod/tagline/iphone/main.json'
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install jsonlint
      run: npm install -g jsonlint

    - name: Lint JSON files android
      run: jsonlint 'prod/tagline/android/main.json'

    - name: Lint JSON files iphone
      run: jsonlint 'prod/tagline/iphone/main.json'
